
###
GET http://localhost:9000/account

###

GET http://localhost:9000/account/1

###

POST http://localhost:9000/account
Content-Type: application/json

{
  "id": null,
  "client_name": "Mikhail Lermontov",
  "balance": 900
}

###


PUT http://localhost:9000/account
Content-Type: application/json

{
  "id": 2,
  "client_name": "Alexander Griboyedov",
  "balance": 800
}

###

DELETE http://localhost:9000/account/5

###

POST http://localhost:9000/transfer
Content-Type: application/json

{
  "id": null,
  "from_account_id": 1,
  "to_account_id": 2,
  "amount": 200,
  "comment": "prosto tak",
  "transfer_date": null
}
###

###
GET http://localhost:9000/transfer/history/1





